version: '3'
services:
  app:
    image: be-runcon
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
