version: '3'
services:
  app:
    image: be-runcon
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
