version: '3'
services:
  app:
    image: be-runcon
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
